# Generated by Django 4.2.5 on 2023-11-11 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_reminder_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('REMINDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.reminder')),
            ],
        ),
    ]
