# Generated by Django 3.2.21 on 2023-11-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Date',
            field=models.DateField(default='2023-11-11'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Date',
            field=models.DateField(default='2023-11-11'),
        ),
    ]
